INSERT INTO currencies (country,currency,code,symbol) VALUES ('Albania','Leke','ALL',N'Lek');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('America','Dollars','USD',N'$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Afghanistan','Afghanis','AFN',N'؋');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Argentina','Pesos','ARS',N'$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Aruba','Guilders','AWG',N'ƒ');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Australia','Dollars','AUD',N'$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Azerbaijan','New Manats','AZN',N'ман');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Bahamas','Dollars','BSD',N'$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Barbados','Dollars','BBD',N'$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Belarus','Rubles','BYR',N'p.');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Belgium','Euro','EUR',N'€');   
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Beliz','Dollars','BZD',N'BZ$');        
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Bermuda','Dollars','BMD',N'$');    
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Bolivia','Bolivianos','BOB',N'$b');    
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Bosnia and Herzegovina','Convertible Marka','BAM',N'KM');      
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Botswana','Pula''s','BWP',N'P');   
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Bulgaria','Leva','BGN',N'лв'); 
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Brazil','Reais','BRL',N'R$');  
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Britain (United Kingdom)','Pounds','GBP',N'£');        
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Brunei Darussalam','Dollars','BND',N'$');      
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Cambodia','Riels','KHR',N'៛'); 
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Canada','Dollars','CAD',N'$');     
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Cayman Islands','Dollars','KYD',N'$');     
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Chile','Pesos','CLP',N'$');    
INSERT INTO currencies (country,currency,code,symbol) VALUES ('China','Yuan Renminbi','CNY',N'¥');    
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Colombia','Pesos','COP',N'$'); 
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Costa Rica','Colón','CRC',N'₡');   
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Croatia','Kuna','HRK',N'kn');  
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Cuba','Pesos','CUP',N'₱');     
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Cyprus','Euro','EUR',N'€');  
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Czech Republic','Koruny','CZK',N'Kč'); 
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Denmark','Kroner','DKK',N'kr');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Dominican Republic','Pesos','DOP ',N'RD$');    
INSERT INTO currencies (country,currency,code,symbol) VALUES ('East Caribbean','Dollars','XCD',N'$'); 
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Egypt','Pounds','EGP',N'£');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('El Salvador','Colones','SVC',N'$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('England (United Kingdom)', 'Pounds', 'GBP',N'£');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Euro','Euro','EUR',N'€');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Falkland Islands','Pounds','FKP',N'£');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Fiji','Dollars','FJD',N'$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('France','Euro','EUR',N'€');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Ghana','Cedis','GHC',N'¢');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Gibraltar','Pounds','GIP',N'£');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Greece','Euro','EUR',N'€');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Guatemala','Quetzales','GTQ',N'Q');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Guernsey','Pounds','GGP',N'£');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Guyana','Dollars','GYD',N'$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Holland (Netherlands)','Euro','EUR',N'€');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Honduras','Lempiras','HNL',N'L');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Hong Kong','Dollars','HKD',N'$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Hungary','Forint','HUF',N'Ft');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Iceland','Kronur','ISK',N'kr');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('India','Rupees','INR',N'Rp');                  
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Indonesia','Rupiahs','IDR',N'Rp');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Iran','Rials','IRR',N'﷼');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Ireland','Euro','EUR',N'€');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Isle of Man','Pounds','IMP',N'£');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Israel','New Shekels','ILS',N'₪');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Italy','Euro','EUR',N'€');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Jamaica','Dollars','JMD',N'J$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Japan','Yen','JPY',N'¥');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Jersey','Pounds','JEP',N'£');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Kazakhstan','Tenge','KZT',N'лв');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Korea (North)','Won','KPW',N'₩');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Korea (South)','Won','KRW',N'₩');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Kyrgyzstan','Soms','KGS',N'лв');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Laos','Kips','LAK',N'₭');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Latvia','Lati','LVL',N'Ls');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Lebanon','Pounds','LBP',N'£');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Liberia','Dollars','LRD',N'$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Liechtenstein','Switzerland Francs','CHF',N'CHF');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Lithuania','Litai','LTL',N'Lt');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Luxembourg','Euro','EUR',N'€');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Macedonia','Denars','MKD',N'ден');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Malaysia','Ringgits','MYR',N'RM');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Malta','Euro','EUR',N'€');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Mauritius','Rupees','MUR',N'₨');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Mexico','Pesos','MXN',N'$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Mongolia','Tugriks','MNT',N'₮');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Mozambique','Meticais','MZN',N'MT');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Namibia','Dollars','NAD',N'$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Nepal','Rupees','NPR',N'₨');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Netherlands Antilles','Guilders','ANG',N'ƒ');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Netherlands','Euro','EUR',N'€');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('New Zealand','Dollars','NZD',N'$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Nicaragua','Cordobas','NIO',N'C$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Nigeria','Nairas','NGN',N'₦');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('North Korea','Won','KPW',N'₩');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Norway','Krone','NOK',N'kr');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Oman','Rials','OMR',N'﷼');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Pakistan','Rupees','PKR',N'₨');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Panama','Balboa','PAB',N'B/.');    
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Paraguay','Guarani','PYG',N'Gs');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Peru','Nuevos Soles','PEN',N'S/.');    
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Philippines','Pesos','PHP',N'Php');    
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Poland','Zlotych','PLN',N'zł');    
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Qatar','Rials','QAR',N'﷼');    
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Romania','New Lei','RON',N'lei');      
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Russia','Rubles','RUB',N'руб');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Saint Helena','Pounds','SHP',N'£');    
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Saudi Arabia','Riyals','SAR',N'﷼');    
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Serbia','Dinars','RSD',N'Дин.');   
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Seychelles','Rupees','SCR',N'₨');  
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Singapore','Dollars','SGD',N'$');  
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Slovenia','Euro','EUR',N'€');  
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Solomon Islands','Dollars','SBD',N'$');    
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Somalia','Shillings','SOS',N'S');  
INSERT INTO currencies (country,currency,code,symbol) VALUES ('South Africa','Rand','ZAR',N'R');  
INSERT INTO currencies (country,currency,code,symbol) VALUES ('South Korea','Won','KRW',N'₩');    
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Spain','Euro','EUR',N'€');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Sri Lanka','Rupees','LKR',N'₨');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Sweden','Kronor','SEK',N'kr');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Switzerland','Francs','CHF',N'CHF');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Suriname','Dollars','SRD',N'$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Syria','Pounds','SYP',N'£');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Taiwan','New Dollars','TWD',N'NT$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Thailand','Baht','THB',N'฿');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Trinidad and Tobago','Dollars','TTD',N'TT$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Turkey','Lira','TRY',N'TL');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Turkey','Liras','TRL',N'£');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Tuvalu','Dollars','TVD',N'$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Ukraine','Hryvnia','UAH',N'₴');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('United Kingdom','Pounds','GBP',N'£');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('United States of America','Dollars','USD',N'$');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Uruguay','Pesos','UYU',N'$U');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Uzbekistan','Sums','UZS',N'лв');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Vatican City','Euro','EUR',N'€');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Venezuela','Bolivares Fuertes','VEF',N'Bs');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Vietnam','Dong','VND',N'₫');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Yemen','Rials','YER',N'﷼');
INSERT INTO currencies (country,currency,code,symbol) VALUES ('Zimbabwe','Zimbabwe Dollars','ZWD',N'Z$');